In [3]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
from pathlib import Path

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt

Project paths

In [10]:
PROJECT_ROOT = Path(
    "/content/drive/MyDrive/project-1/mango-disease-prediction"
)

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

IMAGE_METADATA_FILE = (
    PROCESSED_DIR / "image_metadata.csv"
)

ENVIRONMENTAL_FILE = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "environmental"
    / "environmental.csv"
)

print("Project root:")
print(PROJECT_ROOT)

print("\nImage metadata:")
print(IMAGE_METADATA_FILE)

print("\nEnvironmental data:")
print(ENVIRONMENTAL_FILE)

Project root:
/content/drive/MyDrive/project-1/mango-disease-prediction

Image metadata:
/content/drive/MyDrive/project-1/mango-disease-prediction/data/processed/image_metadata.csv

Environmental data:
/content/drive/MyDrive/project-1/mango-disease-prediction/data/raw/environmental/environmental.csv

In [11]:
print("Image metadata exists:",
      IMAGE_METADATA_FILE.exists())

print("Environmental data exists:",
      ENVIRONMENTAL_FILE.exists())

Image metadata exists: True
Environmental data exists: False

Load image metadata

In [12]:
image_df = pd.read_csv(
    IMAGE_METADATA_FILE
)

print("Image dataset shape:",
      image_df.shape)

print("\nColumns:")
print(image_df.columns.tolist())

display(image_df.head())

Image dataset shape: (4000, 3)

Columns:
['image_path', 'class_name', 'label']

                                          image_path   class_name  label
0  /content/drive/MyDrive/project-1/mango-disease...  Anthracnose      0
1  /content/drive/MyDrive/project-1/mango-disease...  Anthracnose      0
2  /content/drive/MyDrive/project-1/mango-disease...  Anthracnose      0
3  /content/drive/MyDrive/project-1/mango-disease...  Anthracnose      0
4  /content/drive/MyDrive/project-1/mango-disease...  Anthracnose      0

Load environmental data

In [13]:
from pathlib import Path

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/project-1/mango-disease-prediction"
)

matches = list(
    PROJECT_ROOT.rglob("mango_environmental_context_prototype.csv")
)

print("Files found:", len(matches))

for file in matches:
    print(file)

Files found: 1
/content/drive/MyDrive/project-1/mango-disease-prediction/data/raw/environmental/mango_environmental_context_prototype.csv

In [14]:
ENVIRONMENTAL_FILE = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "environmental"
    / "mango_environmental_context_prototype.csv"
)

environmental_df = pd.read_csv(
    ENVIRONMENTAL_FILE
)

print("Shape:", environmental_df.shape)

print("\nColumns:")
print(environmental_df.columns.tolist())

print("\nFirst 5 rows:")
display(environmental_df.head())

Shape: (4000, 11)

Columns:
['sample_id', 'disease', 'date', 'time', 'temperature_c', 'humidity_pct', 'rainfall_mm', 'soil_moisture_pct', 'soil_ph', 'season', 'data_status']

First 5 rows:

,sample_id,disease,date,time,temperature_c,humidity_pct,rainfall_mm,soil_moisture_pct,soil_ph,season,data_status
0,Anthracnose_001,Anthracnose,2021-12-04,09:47:17,25.53,68.01,8.57,76.61,5.95,Winter,SIMULATED
1,Anthracnose_002,Anthracnose,2021-10-01,10:13:14,28.32,80.73,8.96,79.25,6.88,Post-Monsoon,SIMULATED
2,Anthracnose_003,Anthracnose,2021-12-14,12:28:37,24.86,75.92,2.16,67.94,6.15,Winter,SIMULATED
3,Anthracnose_004,Anthracnose,2021-10-25,14:06:05,29.68,78.22,12.23,77.42,6.63,Post-Monsoon,SIMULATED
4,Anthracnose_005,Anthracnose,2021-10-24,16:34:07,30.73,81.10,0.09,68.04,5.89,Post-Monsoon,SIMULATED

Inspect it

In [15]:
print("Data types:")
print(environmental_df.dtypes)

Data types:
sample_id             object
disease               object
date                  object
time                  object
temperature_c        float64
humidity_pct         float64
rainfall_mm          float64
soil_moisture_pct    float64
soil_ph              float64
season                object
data_status           object
dtype: object

In [16]:
print("\nMissing values:")
print(environmental_df.isnull().sum())

Missing values:
sample_id            0
disease              0
date                 0
time                 0
temperature_c        0
humidity_pct         0
rainfall_mm          0
soil_moisture_pct    0
soil_ph              0
season               0
data_status          0
dtype: int64

In [17]:
print("\nDuplicate rows:")
print(environmental_df.duplicated().sum())

Duplicate rows:
0

In [18]:
print("IMAGE DATA")
print("=" * 50)

print("Columns:")
print(image_df.columns.tolist())

print("\nShape:")
print(image_df.shape)

display(image_df.head())


print("\n\nENVIRONMENTAL DATA")
print("=" * 50)

print("Columns:")
print(environmental_df.columns.tolist())

print("\nShape:")
print(environmental_df.shape)

display(environmental_df.head())

IMAGE DATA
==================================================
Columns:
['image_path', 'class_name', 'label']

Shape:
(4000, 3)

                                          image_path   class_name  label
0  /content/drive/MyDrive/project-1/mango-disease...  Anthracnose      0
1  /content/drive/MyDrive/project-1/mango-disease...  Anthracnose      0
2  /content/drive/MyDrive/project-1/mango-disease...  Anthracnose      0
3  /content/drive/MyDrive/project-1/mango-disease...  Anthracnose      0
4  /content/drive/MyDrive/project-1/mango-disease...  Anthracnose      0

ENVIRONMENTAL DATA
==================================================
Columns:
['sample_id', 'disease', 'date', 'time', 'temperature_c', 'humidity_pct', 'rainfall_mm', 'soil_moisture_pct', 'soil_ph', 'season', 'data_status']

Shape:
(4000, 11)

,sample_id,disease,date,time,temperature_c,humidity_pct,rainfall_mm,soil_moisture_pct,soil_ph,season,data_status
0,Anthracnose_001,Anthracnose,2021-12-04,09:47:17,25.53,68.01,8.57,76.61,5.95,Winter,SIMULATED
1,Anthracnose_002,Anthracnose,2021-10-01,10:13:14,28.32,80.73,8.96,79.25,6.88,Post-Monsoon,SIMULATED
2,Anthracnose_003,Anthracnose,2021-12-14,12:28:37,24.86,75.92,2.16,67.94,6.15,Winter,SIMULATED
3,Anthracnose_004,Anthracnose,2021-10-25,14:06:05,29.68,78.22,12.23,77.42,6.63,Post-Monsoon,SIMULATED
4,Anthracnose_005,Anthracnose,2021-10-24,16:34:07,30.73,81.10,0.09,68.04,5.89,Post-Monsoon,SIMULATED

In [19]:
print("Environmental data types:")
print(environmental_df.dtypes)

print("\nEnvironmental missing values:")
print(environmental_df.isnull().sum())

Environmental data types:
sample_id             object
disease               object
date                  object
time                  object
temperature_c        float64
humidity_pct         float64
rainfall_mm          float64
soil_moisture_pct    float64
soil_ph              float64
season                object
data_status           object
dtype: object

Environmental missing values:
sample_id            0
disease              0
date                 0
time                 0
temperature_c        0
humidity_pct         0
rainfall_mm          0
soil_moisture_pct    0
soil_ph              0
season               0
data_status          0
dtype: int64

In [20]:
print("IMAGE DISTRIBUTION")
print("=" * 50)

print(image_df["class_name"].value_counts().sort_index())

print("\nENVIRONMENTAL DISTRIBUTION")
print("=" * 50)

print(environmental_df["disease"].value_counts().sort_index())

IMAGE DISTRIBUTION
==================================================
class_name
Anthracnose         500
Bacterial Canker    500
Cutting Weevil      500
Die Back            500
Gall Midge          500
Healthy             500
Powdery Mildew      500
Sooty Mould         500
Name: count, dtype: int64

ENVIRONMENTAL DISTRIBUTION
==================================================
disease
Anthracnose         500
Bacterial Canker    500
Cutting Weevil      500
Die Back            500
Gall Midge          500
Healthy             500
Powdery Mildew      500
Sooty Mould         500
Name: count, dtype: int64

In [21]:
print("Image total:", len(image_df))
print("Environmental total:", len(environmental_df))

Image total: 4000
Environmental total: 4000

In [22]:
print(
    environmental_df[
        ["sample_id", "disease"]
    ].head(20).to_string(index=False)
)

      sample_id     disease
Anthracnose_001 Anthracnose
Anthracnose_002 Anthracnose
Anthracnose_003 Anthracnose
Anthracnose_004 Anthracnose
Anthracnose_005 Anthracnose
Anthracnose_006 Anthracnose
Anthracnose_007 Anthracnose
Anthracnose_008 Anthracnose
Anthracnose_009 Anthracnose
Anthracnose_010 Anthracnose
Anthracnose_011 Anthracnose
Anthracnose_012 Anthracnose
Anthracnose_013 Anthracnose
Anthracnose_014 Anthracnose
Anthracnose_015 Anthracnose
Anthracnose_016 Anthracnose
Anthracnose_017 Anthracnose
Anthracnose_018 Anthracnose
Anthracnose_019 Anthracnose
Anthracnose_020 Anthracnose

In [ ]:
print(
    environmental_df[
        ["sample_id", "disease"]
    ].tail(20).to_string(index=False)
)

      sample_id     disease
Sooty_Mould_481 Sooty Mould
Sooty_Mould_482 Sooty Mould
Sooty_Mould_483 Sooty Mould
Sooty_Mould_484 Sooty Mould
Sooty_Mould_485 Sooty Mould
Sooty_Mould_486 Sooty Mould
Sooty_Mould_487 Sooty Mould
Sooty_Mould_488 Sooty Mould
Sooty_Mould_489 Sooty Mould
Sooty_Mould_490 Sooty Mould
Sooty_Mould_491 Sooty Mould
Sooty_Mould_492 Sooty Mould
Sooty_Mould_493 Sooty Mould
Sooty_Mould_494 Sooty Mould
Sooty_Mould_495 Sooty Mould
Sooty_Mould_496 Sooty Mould
Sooty_Mould_497 Sooty Mould
Sooty_Mould_498 Sooty Mould
Sooty_Mould_499 Sooty Mould
Sooty_Mould_500 Sooty Mould

In [23]:
image_classes = set(image_df["class_name"].unique())

environmental_classes = set(
    environmental_df["disease"].unique()
)

print("Image classes:")
print(image_classes)

print("\nEnvironmental classes:")
print(environmental_classes)

print("\nClasses missing from environmental data:")
print(image_classes - environmental_classes)

print("\nExtra environmental classes:")
print(environmental_classes - image_classes)

Image classes:
{'Die Back', 'Powdery Mildew', 'Anthracnose', 'Sooty Mould', 'Healthy', 'Bacterial Canker', 'Gall Midge', 'Cutting Weevil'}

Environmental classes:
{'Die Back', 'Powdery Mildew', 'Anthracnose', 'Sooty Mould', 'Healthy', 'Bacterial Canker', 'Gall Midge', 'Cutting Weevil'}

Classes missing from environmental data:
set()

Extra environmental classes:
set()

In [ ]:
image_counts = (
    image_df["class_name"]
    .value_counts()
    .sort_index()
)

environmental_counts = (
    environmental_df["disease"]
    .value_counts()
    .sort_index()
)

comparison = pd.DataFrame({
    "image_count": image_counts,
    "environmental_count": environmental_counts
})

comparison["difference"] = (
    comparison["image_count"]
    - comparison["environmental_count"]
)

display(comparison)

                  image_count  environmental_count  difference
Anthracnose               500                  500           0
Bacterial Canker          500                  500           0
Cutting Weevil            500                  500           0
Die Back                  500                  500           0
Gall Midge                500                  500           0
Healthy                   500                  500           0
Powdery Mildew            500                  500           0
Sooty Mould               500                  500           0

In [ ]:
image_data = image_df.copy()
environmental_data = environmental_df.copy()

In [ ]:
image_data = image_data.sort_values(
    ["class_name", "image_path"]
).reset_index(drop=True)

environmental_data = environmental_data.sort_values(
    ["disease", "sample_id"]
).reset_index(drop=True)

In [ ]:
image_data["sample_index"] = (
    image_data
    .groupby("class_name")
    .cumcount()
)

environmental_data["sample_index"] = (
    environmental_data
    .groupby("disease")
    .cumcount()
)

Merge the two datasets

In [ ]:
paired_df = image_data.merge(
    environmental_data,
    left_on=["class_name", "sample_index"],
    right_on=["disease", "sample_index"],
    how="inner"
)

In [ ]:
print("Paired samples:", len(paired_df))

print("\nColumns:")
print(paired_df.columns.tolist())

display(paired_df.head())

Paired samples: 4000

Columns:
['image_path', 'class_name', 'label', 'sample_index', 'sample_id', 'disease', 'date', 'time', 'temperature_c', 'humidity_pct', 'rainfall_mm', 'soil_moisture_pct', 'soil_ph', 'season', 'data_status']

,image_path,class_name,label,sample_index,sample_id,disease,date,time,temperature_c,humidity_pct,rainfall_mm,soil_moisture_pct,soil_ph,season,data_status
0,/content/drive/MyDrive/project-1/mango-disease...,Anthracnose,0,0,Anthracnose_001,Anthracnose,2021-12-04,09:47:17,25.53,68.01,8.57,76.61,5.95,Winter,SIMULATED
1,/content/drive/MyDrive/project-1/mango-disease...,Anthracnose,0,1,Anthracnose_002,Anthracnose,2021-10-01,10:13:14,28.32,80.73,8.96,79.25,6.88,Post-Monsoon,SIMULATED
2,/content/drive/MyDrive/project-1/mango-disease...,Anthracnose,0,2,Anthracnose_003,Anthracnose,2021-12-14,12:28:37,24.86,75.92,2.16,67.94,6.15,Winter,SIMULATED
3,/content/drive/MyDrive/project-1/mango-disease...,Anthracnose,0,3,Anthracnose_004,Anthracnose,2021-10-25,14:06:05,29.68,78.22,12.23,77.42,6.63,Post-Monsoon,SIMULATED
4,/content/drive/MyDrive/project-1/mango-disease...,Anthracnose,0,4,Anthracnose_005,Anthracnose,2021-10-24,16:34:07,30.73,81.10,0.09,68.04,5.89,Post-Monsoon,SIMULATED

remove redundant column

In [ ]:
paired_df = paired_df.drop(
    columns=["disease"]
)

In [ ]:
display(paired_df.head())

,image_path,class_name,label,sample_index,sample_id,date,time,temperature_c,humidity_pct,rainfall_mm,soil_moisture_pct,soil_ph,season,data_status
0,/content/drive/MyDrive/project-1/mango-disease...,Anthracnose,0,0,Anthracnose_001,2021-12-04,09:47:17,25.53,68.01,8.57,76.61,5.95,Winter,SIMULATED
1,/content/drive/MyDrive/project-1/mango-disease...,Anthracnose,0,1,Anthracnose_002,2021-10-01,10:13:14,28.32,80.73,8.96,79.25,6.88,Post-Monsoon,SIMULATED
2,/content/drive/MyDrive/project-1/mango-disease...,Anthracnose,0,2,Anthracnose_003,2021-12-14,12:28:37,24.86,75.92,2.16,67.94,6.15,Winter,SIMULATED
3,/content/drive/MyDrive/project-1/mango-disease...,Anthracnose,0,3,Anthracnose_004,2021-10-25,14:06:05,29.68,78.22,12.23,77.42,6.63,Post-Monsoon,SIMULATED
4,/content/drive/MyDrive/project-1/mango-disease...,Anthracnose,0,4,Anthracnose_005,2021-10-24,16:34:07,30.73,81.10,0.09,68.04,5.89,Post-Monsoon,SIMULATED

Check the pairing

In [ ]:
print("Total paired samples:", len(paired_df))

print("\nDisease distribution:")
print(
    paired_df["class_name"]
    .value_counts()
    .sort_index()
)

Total paired samples: 4000

Disease distribution:
class_name
Anthracnose         500
Bacterial Canker    500
Cutting Weevil      500
Die Back            500
Gall Midge          500
Healthy             500
Powdery Mildew      500
Sooty Mould         500
Name: count, dtype: int64

Check environmental features

In [ ]:
ENVIRONMENTAL_FEATURES = [
    "temperature_c",
    "humidity_pct",
    "rainfall_mm",
    "soil_moisture_pct",
    "soil_ph",
    "season"
]

print(paired_df[ENVIRONMENTAL_FEATURES].head())

   temperature_c  humidity_pct  rainfall_mm  soil_moisture_pct  soil_ph  \
0          25.53         68.01         8.57              76.61     5.95
1          28.32         80.73         8.96              79.25     6.88
2          24.86         75.92         2.16              67.94     6.15
3          29.68         78.22        12.23              77.42     6.63
4          30.73         81.10         0.09              68.04     5.89

         season
0        Winter
1  Post-Monsoon
2        Winter
3  Post-Monsoon
4  Post-Monsoon

In [ ]:
print(
    paired_df[ENVIRONMENTAL_FEATURES]
    .isnull()
    .sum()
)

temperature_c        0
humidity_pct         0
rainfall_mm          0
soil_moisture_pct    0
soil_ph              0
season               0
dtype: int64

In [ ]:
PAIRED_FILE = (
    PROCESSED_DIR / "paired_metadata.csv"
)

paired_df.to_csv(
    PAIRED_FILE,
    index=False
)

print("✅ Paired metadata saved:")
print(PAIRED_FILE)

✅ Paired metadata saved:
/content/drive/MyDrive/project-1/mango-disease-prediction/data/processed/paired_metadata.csv

Train/validation/test split

In [ ]:
train_df, temp_df = train_test_split(
    paired_df,
    test_size=0.30,
    random_state=42,
    stratify=paired_df["label"]
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    random_state=42,
    stratify=temp_df["label"]
)

print("Train:", len(train_df))
print("Validation:", len(val_df))
print("Test:", len(test_df))

Train: 2800
Validation: 600
Test: 600

Verify no leakage

In [ ]:
train_paths = set(train_df["image_path"])
val_paths = set(val_df["image_path"])
test_paths = set(test_df["image_path"])

print(
    "Train ∩ Validation:",
    len(train_paths & val_paths)
)

print(
    "Train ∩ Test:",
    len(train_paths & test_paths)
)

print(
    "Validation ∩ Test:",
    len(val_paths & test_paths)
)

Train ∩ Validation: 0
Train ∩ Test: 0
Validation ∩ Test: 0

Save the splits

In [ ]:
train_df.to_csv(
    PROCESSED_DIR / "train.csv",
    index=False
)

val_df.to_csv(
    PROCESSED_DIR / "validation.csv",
    index=False
)

test_df.to_csv(
    PROCESSED_DIR / "test.csv",
    index=False
)

print("✅ Train/validation/test files saved.")

✅ Train/validation/test files saved.

Step 1 — Load the processed CSVs

In [4]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/project-1/mango-disease-prediction"
)

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

train_df = pd.read_csv(
    PROCESSED_DIR / "train.csv"
)

val_df = pd.read_csv(
    PROCESSED_DIR / "validation.csv"
)

test_df = pd.read_csv(
    PROCESSED_DIR / "test.csv"
)

print("Train:", len(train_df))
print("Validation:", len(val_df))
print("Test:", len(test_df))

Train: 2800
Validation: 600
Test: 600

Step 2 — Load environmental preprocessing

In [6]:
%%writefile /content/drive/MyDrive/project-1/mango-disease-prediction/src/preprocessing/environmental_preprocessing.py

import numpy as np

from sklearn.preprocessing import (
    StandardScaler,
    OneHotEncoder
)


# ==========================================
# ENVIRONMENTAL FEATURES
# ==========================================

NUMERICAL_FEATURES = [
    "temperature_c",
    "humidity_pct",
    "rainfall_mm",
    "soil_moisture_pct",
    "soil_ph"
]

CATEGORICAL_FEATURES = [
    "season"
]


# ==========================================
# PREPROCESSORS
# ==========================================

numerical_scaler = StandardScaler()

season_encoder = OneHotEncoder(
    sparse_output=False,
    handle_unknown="ignore"
)


# ==========================================
# FIT PREPROCESSORS
# ==========================================

def fit_preprocessors(train_df):
    """
    Fit the environmental preprocessing objects.

    IMPORTANT:
    Only the training dataset should be used
    to fit the scaler and encoder.
    """

    numerical_scaler.fit(
        train_df[NUMERICAL_FEATURES]
    )

    season_encoder.fit(
        train_df[CATEGORICAL_FEATURES]
    )


# ==========================================
# TRANSFORM ENVIRONMENTAL DATA
# ==========================================

def transform_environmental_data(df):
    """
    Transform environmental data using the
    already-fitted scaler and encoder.
    """

    # Scale numerical features
    numerical_data = numerical_scaler.transform(
        df[NUMERICAL_FEATURES]
    )

    # Encode season
    season_data = season_encoder.transform(
        df[CATEGORICAL_FEATURES]
    )

    # Combine numerical + categorical features
    combined_data = np.concatenate(
        [
            numerical_data,
            season_data
        ],
        axis=1
    )

    return combined_data

Overwriting /content/drive/MyDrive/project-1/mango-disease-prediction/src/preprocessing/environmental_preprocessing.py

Important: reload the module

In [7]:
import importlib

import src.preprocessing.environmental_preprocessing as environmental_preprocessing

importlib.reload(environmental_preprocessing)

Test it with your training data

In [8]:
print(len(train_df))
print(len(val_df))
print(len(test_df))

2800
600
600

In [29]:
from pathlib import Path

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/project-1/mango-disease-prediction"
)

print("Project exists:", PROJECT_ROOT.exists())

Project exists: True

In [31]:
import sys

PROJECT_ROOT_STR = str(PROJECT_ROOT)

if PROJECT_ROOT_STR not in sys.path:
    sys.path.insert(0, PROJECT_ROOT_STR)

print("Project path added.")

Project path added.

In [32]:
import importlib

import src.preprocessing.environmental_preprocessing as environmental_preprocessing

importlib.reload(
    environmental_preprocessing
)

print("Module reloaded.")

Module reloaded.

In [33]:
from src.preprocessing.environmental_preprocessing import (
    NUMERICAL_FEATURES,
    CATEGORICAL_FEATURES,
    fit_preprocessors,
    transform_environmental_data
)

print("✅ Functions imported successfully.")

✅ Functions imported successfully.

In [34]:
print("train_df exists:", "train_df" in globals())

train_df exists: True

In [35]:
import pandas as pd

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

train_df = pd.read_csv(
    PROCESSED_DIR / "train.csv"
)

val_df = pd.read_csv(
    PROCESSED_DIR / "validation.csv"
)

test_df = pd.read_csv(
    PROCESSED_DIR / "test.csv"
)

print("Train:", len(train_df))
print("Validation:", len(val_df))
print("Test:", len(test_df))

Train: 2800
Validation: 600
Test: 600

In [36]:
fit_preprocessors(train_df)

print("✅ Preprocessors fitted using TRAINING data only.")

✅ Preprocessors fitted using TRAINING data only.

In [37]:
train_environment = transform_environmental_data(
    train_df
)

val_environment = transform_environmental_data(
    val_df
)

test_environment = transform_environmental_data(
    test_df
)

print("Train:", train_environment.shape)
print("Validation:", val_environment.shape)
print("Test:", test_environment.shape)

Train: (2800, 7)
Validation: (600, 7)
Test: (600, 7)

In [38]:
import torch

train_environment = torch.tensor(
    train_environment,
    dtype=torch.float32
)

val_environment = torch.tensor(
    val_environment,
    dtype=torch.float32
)

test_environment = torch.tensor(
    test_environment,
    dtype=torch.float32
)

print("Train environment:", train_environment.shape)
print("Validation environment:", val_environment.shape)
print("Test environment:", test_environment.shape)

Train environment: torch.Size([2800, 7])
Validation environment: torch.Size([600, 7])
Test environment: torch.Size([600, 7])

Import image preprocessing

In [40]:
%%writefile /content/drive/MyDrive/project-1/mango-disease-prediction/src/preprocessing/image_preprocessing.py

from torchvision import transforms


# ==========================================
# IMAGE SETTINGS
# ==========================================

IMAGE_SIZE = 224

IMAGENET_MEAN = [
    0.485,
    0.456,
    0.406
]

IMAGENET_STD = [
    0.229,
    0.224,
    0.225
]


# ==========================================
# TRAINING TRANSFORM
# ==========================================

train_transform = transforms.Compose([

    transforms.Resize(
        (IMAGE_SIZE, IMAGE_SIZE)
    ),

    transforms.RandomHorizontalFlip(
        p=0.5
    ),

    transforms.RandomRotation(
        degrees=15
    ),

    transforms.ColorJitter(
        brightness=0.2,
        contrast=0.2,
        saturation=0.2
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=IMAGENET_MEAN,
        std=IMAGENET_STD
    )
])


# ==========================================
# VALIDATION / TEST TRANSFORM
# ==========================================

val_test_transform = transforms.Compose([

    transforms.Resize(
        (IMAGE_SIZE, IMAGE_SIZE)
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=IMAGENET_MEAN,
        std=IMAGENET_STD
    )
])

Overwriting /content/drive/MyDrive/project-1/mango-disease-prediction/src/preprocessing/image_preprocessing.py

Reload the file

In [41]:
import importlib

import src.preprocessing.image_preprocessing as image_preprocessing

importlib.reload(
    image_preprocessing
)

print("Image preprocessing module reloaded.")

Image preprocessing module reloaded.

In [42]:
from src.preprocessing.image_preprocessing import (
    train_transform,
    val_test_transform,
    IMAGE_SIZE
)

print("✅ Image preprocessing imported!")
print("Image size:", IMAGE_SIZE)

✅ Image preprocessing imported!
Image size: 224

Verify the transformations exist

In [43]:
print("Train transform:")
print(train_transform)

print("\nValidation/Test transform:")
print(val_test_transform)

Train transform:
Compose(
    Resize(size=(224, 224), interpolation=bilinear, max_size=None, antialias=True)
    RandomHorizontalFlip(p=0.5)
    RandomRotation(degrees=[-15.0, 15.0], interpolation=nearest, expand=False, fill=0)
    ColorJitter(brightness=(0.8, 1.2), contrast=(0.8, 1.2), saturation=(0.8, 1.2), hue=None)
    ToTensor()
    Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
)

Validation/Test transform:
Compose(
    Resize(size=(224, 224), interpolation=bilinear, max_size=None, antialias=True)
    ToTensor()
    Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
)

In [44]:
from PIL import Image

sample_path = train_df.iloc[0]["image_path"]

image = Image.open(
    sample_path
).convert("RGB")

print("Original size:", image.size)

Original size: (240, 320)

In [45]:
transformed_image = train_transform(image)

print(
    "Transformed shape:",
    transformed_image.shape
)

Transformed shape: torch.Size([3, 224, 224])